# =====================
# Secret DB credentials
# =====================
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: wordpress
type: Opaque
stringData:
  mariadb-root-password: rootpass
  mariadb-database: wordpress
  mariadb-user: wpuser
  mariadb-password: wppass
